### ISSUE TITLE
consider license: "UNLICENSED" as UNLICENSED not WTFPL

### ISSUE THREAD

**Issue by graingert** [iandotkelly/nlf#34] opened 2016-02-03 10:29 UTC
currently nlf considers my proprietary app licensed under WTFPL

**Comment by iandotkelly** [comment] 2016-02-03 15:05
Ewww.... that's not right. I'll look at this tonight.

**Comment by iandotkelly** [comment] 2016-02-04 02:06
You're going to have to give me some information as to why nlf is returning WTFPL.

I've tried a missing "license" property in package.json and an UNLICENSED value in that property. Is this from a package.json value its seeing or is it finding a " WTFPL " string (including spaces) in a readme or license file.

**Comment by graingert** [comment] 2016-02-04 09:17
there's no README or LICENSE file...

**Comment by iandotkelly** [comment] 2016-02-04 14:18
I'm willing to put in the effort to diagnose and fix this issue, but I need some more to go on than the lack of README or LICENSE files.  I cannot reproduce this problem by making an UNLICENSED module.

Can you provide the output from NLF, which will show me whether the WTFPL is coming from a file or a package.json file - if you need to rename your module in the output to keep its name from the public that is fine.  Also if you were able to post a package.json file (again you can rename information like the name, description, author etc).... this would also help.

**Comment by graingert** [comment] 2016-02-04 14:50
Makes sense, I'll try and create a minimal failing package

**Comment by iandotkelly** [comment] 2016-03-18 01:05
Closing until a minimal failing package is provided.

**Closed by iandotkelly** 2016-03-18 01:05 UTC
