### ISSUE TITLE
NPM 3 dedupe support

### ISSUE THREAD

**Issue by bluejamesbond** [iandotkelly/nlf#30] opened 2015-11-13 05:50 UTC
Include only modoules declared in the current project's package.json

**Comment by tkrugg** [comment] 2016-02-05 14:45
+1, although i would have called this npm 3 dedupe support

**Comment by iandotkelly** [comment] 2016-07-09 17:34
So unless I misunderstand this - you are asking for just the 'top level' dependencies of a project.  This can be retrieved through the following:

```
nlf -r 0
```

Please let me know if I've misunderstood.  I'll close this in the meantime.

**Comment by hairyhenderson** [comment] 2016-08-31 17:28
@iandotkelly - the issue is that npm 3 flattens dependencies:

```console
$ ls -alh node_modules | wc -l
430
$ jq '.dependencies | length' package.json
24
$ nlf -r 0 -d --csv | wc -l 
336
```

`nlf`'s number is lower because `node_modules` has devdependencies as well, but the number _should_ be 24 :)

**Comment by subesokun** [comment] 2016-09-07 07:35
@iandotkelly Please reopen this issue. As @hairyhenderson mentioned already npm 3 flattens the dependencies in the node_modules folder and hence a `-r 0` will no longer return only the direct child dependencies.

**Comment by subesokun** [comment] 2017-02-07 10:21
Any update on this issue :( ?

**Comment by iandotkelly** [comment] 2017-05-06 19:01
Finally fixed with https://github.com/iandotkelly/nlf/releases/tag/2.0.0

**Closed by iandotkelly** 2017-05-06 19:01 UTC

**Comment by hairyhenderson** [comment] 2017-05-06 23:10
Thank you, @iandotkelly!
